# This file is generated by Dist::Zilla::Plugin::CPANFile v6.036
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "Attribute::Handlers" => "0";
requires "Exporter::Tiny" => "0";
requires "Ref::Util" => "0";
requires "namespace::clean" => "0";
requires "parent" => "0";
requires "perl" => "5.014";
requires "strict" => "0";
requires "warnings" => "0";

on 'build' => sub {
  requires "Module::Build" => "0.28";
};

on 'test' => sub {
  requires "Test::More" => "0";
  requires "Test::Warnings" => "0";
  requires "Test::YAFT" => "0";
  requires "require::relative" => "0";
};

on 'configure' => sub {
  requires "Module::Build" => "0.28";
};

on 'develop' => sub {
  requires "Test::More" => "0";
  requires "Test::Pod" => "1.41";
};
