
use v5.14;
use warnings;

use require::relative "../../test-helper.pl";

use Scalar::Util qw[ refaddr ];

it "ppi_transform() should not process any where/invoke when element is not a PPI::Element"
	=> expect => 0
	=> got    => ppix_transform (
		'PPI::Element'
		=> where { fail "where should not be called" }
		=> invoke { fail "invoke should not be called" }
	);

it "ppi_transform() should not run any invoke when where is missing"
	=> expect => 0
	=> got    => ppix_transform (
		document ('')
		=> invoke { fail "invoke should not be called" }
	);

it "ppi_transform() should not run any where when invoke is missing"
	=> expect => 0
	=> got    => ppix_transform (
		document ('')
		=> where { fail "where should not be called" }
	);

my $document = document "0x1;0x2;3;";
it "ppi_transform() should not process same element twice"
	=> expect => 3 # 1 and 2; plus 2 generated by invoke for 1
	=> got    => ppix_transform (
		$document
		=> where { it_is_token_number }
		=> where { current->literal < 3 }
		=> invoke {
			current->insert_before (PPI::Token::Number->new (current->literal + 1));
			current->insert_before (PPI::Token::Structure->new (';'));
		}
	);

it "ppi_transform() should modify document"
	=> got    => $document->serialize
	=> expect => "3;2;0x1;3;0x2;3;"
	;

had_no_warnings;

done_testing;

