---
name: build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  # allow to trigger workflow manually
  workflow_dispatch:

  # once a month check if still runs (newer dependencies - perl, libraries, actions, ...)
  schedule:
    - cron: 0 0 1 * *

jobs:
  simple-perltester-workflow:
    uses: perl-actions/github-workflows/.github/workflows/simple-perltester-workflow.yml@main
    with:
      since-perl: 5.14
